-- CORTEX AI ANALYTICS: Which EV Manufacturers Are Growing Fastest?
CREATE OR REPLACE TABLE EV_ANALYTICS_DB.CORTEX_AI_ANALYTICS.EV_FASTEST_GROWING_MANUFACTURERS AS
 WITH yearly_by_make AS (
    SELECT
        s.MAKE,
        s.MODEL_YEAR,
        COUNT(DISTINCT s.VIN) AS VEHICLES
    FROM EV_ANALYTICS_DB.SILVER.EV_POPULATION_SILVER s
     WHERE s.MODEL_YEAR BETWEEN 2022 AND 2025
    GROUP BY s.MAKE, s.MODEL_YEAR
),
pivoted AS (
    SELECT
        MAKE,
        SUM(CASE WHEN MODEL_YEAR = 2022 THEN VEHICLES ELSE 0 END) AS VEHICLES_2022,
        SUM(CASE WHEN MODEL_YEAR = 2023 THEN VEHICLES ELSE 0 END) AS VEHICLES_2023,
        SUM(CASE WHEN MODEL_YEAR = 2024 THEN VEHICLES ELSE 0 END) AS VEHICLES_2024,
        SUM(CASE WHEN MODEL_YEAR = 2025 THEN VEHICLES ELSE 0 END) AS VEHICLES_2025,
        SUM(VEHICLES) AS TOTAL_VEHICLES_2022_2025
    FROM yearly_by_make
    GROUP BY MAKE
    HAVING SUM(CASE WHEN MODEL_YEAR = 2023 THEN VEHICLES ELSE 0 END) >= 10
)
SELECT
    p.MAKE,
    a.TOTAL_VEHICLES AS ALL_TIME_TOTAL_VEHICLES,
    a.MARKET_SHARE_PCT,
    p.VEHICLES_2022,
    p.VEHICLES_2023,
    p.VEHICLES_2024,
    p.VEHICLES_2025,
    p.TOTAL_VEHICLES_2022_2025,
    ROUND((p.VEHICLES_2024 - p.VEHICLES_2023) * 100.0 / NULLIF(p.VEHICLES_2023, 0), 2) AS GROWTH_2023_TO_2024_PCT,
    ROUND((p.VEHICLES_2025 - p.VEHICLES_2024) * 100.0 / NULLIF(p.VEHICLES_2024, 0), 2) AS GROWTH_2024_TO_2025_PCT,
    ROUND((p.VEHICLES_2025 - p.VEHICLES_2022) * 100.0 / NULLIF(p.VEHICLES_2022, 0), 2) AS CAGR_2022_TO_2025_PCT,
    a.BEV_COUNT,
    a.PHEV_COUNT,
    ROUND(a.BEV_COUNT * 100.0 / NULLIF(a.TOTAL_VEHICLES, 0), 2) AS BEV_RATIO_PCT,
    a.AVG_ELECTRIC_RANGE,
    CURRENT_TIMESTAMP() AS ANALYSIS_TIMESTAMP
FROM pivoted p
JOIN EV_ANALYTICS_DB.GOLD.EV_ADOPTION_BY_MANUFACTURER a
    ON p.MAKE = a.MAKE
ORDER BY GROWTH_2024_TO_2025_PCT DESC;

select * from EV_ANALYTICS_DB.CORTEX_AI_ANALYTICS.EV_FASTEST_GROWING_MANUFACTURERS;

-- CORTEX AI ANALYTICS: Which Regions Require Charging Infrastructure Expansion?
CREATE OR REPLACE TABLE EV_ANALYTICS_DB.CORTEX_AI_ANALYTICS.EV_CHARGING_INFRASTRUCTURE_NEEDS AS
WITH regional_demand AS (
    SELECT
        COUNTY,
        CITY,
        POSTAL_CODE,
        ELECTRIC_UTILITY,
        COUNT(DISTINCT VIN) AS TOTAL_VEHICLES,
        SUM(CASE WHEN ELECTRIC_VEHICLE_TYPE = 'Battery Electric Vehicle (BEV)' THEN 1 ELSE 0 END) AS BEV_COUNT,
        SUM(CASE WHEN ELECTRIC_VEHICLE_TYPE = 'Plug-in Hybrid Electric Vehicle (PHEV)' THEN 1 ELSE 0 END) AS PHEV_COUNT,
        ROUND(AVG(ELECTRIC_RANGE), 2) AS AVG_ELECTRIC_RANGE,
        COUNT(DISTINCT MAKE) AS DISTINCT_MAKES,
        COUNT(DISTINCT MODEL) AS DISTINCT_MODELS,
        MIN(MODEL_YEAR) AS EARLIEST_MODEL_YEAR,
        MAX(MODEL_YEAR) AS LATEST_MODEL_YEAR,
        SUM(CASE WHEN MODEL_YEAR >= 2023 THEN 1 ELSE 0 END) AS RECENT_VEHICLES_2023_PLUS
    FROM EV_ANALYTICS_DB.SILVER.EV_POPULATION_SILVER
    GROUP BY COUNTY, CITY, POSTAL_CODE, ELECTRIC_UTILITY
),
county_totals AS (
    SELECT
        COUNTY,
        SUM(TOTAL_VEHICLES) AS COUNTY_TOTAL_VEHICLES
    FROM regional_demand
    GROUP BY COUNTY
),
utility_demand AS (
    SELECT
        ELECTRIC_UTILITY,
        TOTAL_VEHICLES AS UTILITY_TOTAL_VEHICLES,
        DEMAND_SHARE_PCT AS UTILITY_DEMAND_SHARE_PCT
    FROM EV_ANALYTICS_DB.GOLD.EV_UTILITY_PROVIDER_DEMAND
)
SELECT
    r.COUNTY,
    r.CITY,
    r.POSTAL_CODE,
    r.ELECTRIC_UTILITY,
    r.TOTAL_VEHICLES,
    ROUND(r.TOTAL_VEHICLES * 100.0 / SUM(r.TOTAL_VEHICLES) OVER (), 2) AS OVERALL_DEMAND_SHARE_PCT,
    ct.COUNTY_TOTAL_VEHICLES,
    ROUND(r.TOTAL_VEHICLES * 100.0 / NULLIF(ct.COUNTY_TOTAL_VEHICLES, 0), 2) AS CITY_SHARE_IN_COUNTY_PCT,
    r.BEV_COUNT,
    r.PHEV_COUNT,
    ROUND(r.BEV_COUNT * 100.0 / NULLIF(r.TOTAL_VEHICLES, 0), 2) AS BEV_RATIO_PCT,
    r.AVG_ELECTRIC_RANGE,
    r.DISTINCT_MAKES,
    r.DISTINCT_MODELS,
    r.RECENT_VEHICLES_2023_PLUS,
    ROUND(r.RECENT_VEHICLES_2023_PLUS * 100.0 / NULLIF(r.TOTAL_VEHICLES, 0), 2) AS RECENT_ADOPTION_PCT,
    ud.UTILITY_TOTAL_VEHICLES,
    ud.UTILITY_DEMAND_SHARE_PCT,
    CASE
        WHEN r.TOTAL_VEHICLES >= 100 AND r.BEV_COUNT * 100.0 / NULLIF(r.TOTAL_VEHICLES, 0) >= 60 THEN 'CRITICAL'
        WHEN r.TOTAL_VEHICLES >= 50 AND r.BEV_COUNT * 100.0 / NULLIF(r.TOTAL_VEHICLES, 0) >= 50 THEN 'HIGH'
        WHEN r.TOTAL_VEHICLES >= 20 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS INFRASTRUCTURE_PRIORITY,
    CURRENT_TIMESTAMP() AS ANALYSIS_TIMESTAMP
FROM regional_demand r
JOIN county_totals ct ON r.COUNTY = ct.COUNTY
LEFT JOIN utility_demand ud ON r.ELECTRIC_UTILITY = ud.ELECTRIC_UTILITY
ORDER BY r.TOTAL_VEHICLES DESC;

select * from EV_ANALYTICS_DB.CORTEX_AI_ANALYTICS.EV_CHARGING_INFRASTRUCTURE_NEEDS limit 10;
select count(*) from EV_ANALYTICS_DB.CORTEX_AI_ANALYTICS.EV_CHARGING_INFRASTRUCTURE_NEEDS;



-- CORTEX AI ANALYTICS: Which EV Types Have Highest Electric Range?
CREATE OR REPLACE TABLE EV_ANALYTICS_DB.CORTEX_AI_ANALYTICS.EV_TYPE_RANGE_ANALYSIS AS
WITH type_make_detail AS (
    SELECT
        s.ELECTRIC_VEHICLE_TYPE,
        s.MAKE,
        s.MODEL,
        COUNT(DISTINCT s.VIN) AS TOTAL_VEHICLES,
        ROUND(AVG(s.ELECTRIC_RANGE), 2) AS AVG_ELECTRIC_RANGE,
        MIN(s.ELECTRIC_RANGE) AS MIN_ELECTRIC_RANGE,
        MAX(s.ELECTRIC_RANGE) AS MAX_ELECTRIC_RANGE,
        SUM(CASE WHEN s.ELECTRIC_RANGE > 0 THEN 1 ELSE 0 END) AS VEHICLES_WITH_RANGE_DATA,
        ROUND(SUM(CASE WHEN s.ELECTRIC_RANGE > 0 THEN 1 ELSE 0 END) * 100.0
              / NULLIF(COUNT(*), 0), 2) AS RANGE_DATA_COVERAGE_PCT,
        MIN(s.MODEL_YEAR) AS EARLIEST_MODEL_YEAR,
        MAX(s.MODEL_YEAR) AS LATEST_MODEL_YEAR
    FROM EV_ANALYTICS_DB.SILVER.EV_POPULATION_SILVER s
    GROUP BY s.ELECTRIC_VEHICLE_TYPE, s.MAKE, s.MODEL
),
ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (PARTITION BY ELECTRIC_VEHICLE_TYPE ORDER BY AVG_ELECTRIC_RANGE DESC) AS RANGE_RANK_IN_TYPE,
        ROUND(AVG_ELECTRIC_RANGE - AVG(AVG_ELECTRIC_RANGE) OVER (PARTITION BY ELECTRIC_VEHICLE_TYPE), 2) AS RANGE_VS_TYPE_AVG,
        ROUND(TOTAL_VEHICLES * 100.0 / SUM(TOTAL_VEHICLES) OVER (PARTITION BY ELECTRIC_VEHICLE_TYPE), 2) AS SHARE_WITHIN_TYPE_PCT
    FROM type_make_detail
    WHERE VEHICLES_WITH_RANGE_DATA > 0
)
SELECT
    ELECTRIC_VEHICLE_TYPE,
    MAKE,
    MODEL,
    TOTAL_VEHICLES,
    AVG_ELECTRIC_RANGE,
    MIN_ELECTRIC_RANGE,
    MAX_ELECTRIC_RANGE,
    VEHICLES_WITH_RANGE_DATA,
    RANGE_DATA_COVERAGE_PCT,
    RANGE_RANK_IN_TYPE,
    RANGE_VS_TYPE_AVG,
    SHARE_WITHIN_TYPE_PCT,
    EARLIEST_MODEL_YEAR,
    LATEST_MODEL_YEAR,
    CURRENT_TIMESTAMP() AS ANALYSIS_TIMESTAMP
FROM ranked
ORDER BY ELECTRIC_VEHICLE_TYPE, RANGE_RANK_IN_TYPE;

select * from EV_ANALYTICS_DB.CORTEX_AI_ANALYTICS.EV_TYPE_RANGE_ANALYSIS limit 10;
select count(*) from EV_ANALYTICS_DB.CORTEX_AI_ANALYTICS.EV_TYPE_RANGE_ANALYSiS;





-- CORTEX AI ANALYTICS: AI Executive Summaries for EV Manufacturers
CREATE OR REPLACE TABLE EV_ANALYTICS_DB.CORTEX_AI_ANALYTICS.AI_EXECUTIVE_SUMMARIES AS
SELECT
    m.MAKE,
    m.TOTAL_VEHICLES,
    m.MARKET_SHARE_PCT,
    m.BEV_COUNT,
    m.PHEV_COUNT,
    m.AVG_ELECTRIC_RANGE,
    SNOWFLAKE.CORTEX.COMPLETE(
        'mistral-large',
        CONCAT(
            'You are a senior automotive industry analyst. Generate a concise executive summary for the EV manufacturer: ', m.MAKE, '. ',
            'Use the following data points to provide insights on market positioning, growth potential, and competitive analysis. ',
            'Data: ',
            'Total Vehicles Registered: ', m.TOTAL_VEHICLES::STRING, '. ' ,
            'Market Share: ', m.MARKET_SHARE_PCT::STRING, '%. ',
            'BEV (Battery Electric) Count: ', m.BEV_COUNT::STRING, '. ' ,
            'PHEV (Plug-in Hybrid) Count: ', m.PHEV_COUNT::STRING, '. ' ,
            'Average Electric Range: ', m.AVG_ELECTRIC_RANGE::STRING, ' miles. ',
            'Total Models Offered: ', m.TOTAL_MODELS::STRING, '. ',
            'Years in Market: ', m.YEARS_IN_MARKET::STRING, ' (', m.EARLIEST_MODEL_YEAR::STRING, ' - ', m.LATEST_MODEL_YEAR::STRING, '). ',
            'Cover these sections in 3-4 sentences each: ',
            '1) Market Positioning - current standing and brand strength. ',
            '2) Growth Insights - trajectory and electrification strategy (BEV vs PHEV mix). ',
            '3) Competitive Analysis - strengths, weaknesses, and how they compare to the broader EV market.'
        )
    ) AS AI_EXECUTIVE_SUMMARY,
    CURRENT_TIMESTAMP() AS GENERATED_AT
FROM EV_ANALYTICS_DB.GOLD.EV_ADOPTION_BY_MANUFACTURER m
ORDER BY m.TOTAL_VEHICLES DESC;